version: "3.8"

services:

  db_projeto03:
    container_name: database_projeto03
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto03_database
    volumes:
      - pgdata:/data/postgresql

  app:
    build: .
    container_name: projeto03
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto03
    depends_on:
      - db_projeto03

volumes:
  pgdata:
    driver: local
